name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Step 4: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t loan-approval-predictor .
    
    # # Step 6: Run tests
    # - name: Run tests
    #   run: |
    #     python -m unittest discover tests/

    # Step 7: Log in to DockerHub
    - name: Log in to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    # Step 8: Tag Docker image
    - name: Tag Docker image
      run: |
        docker tag medical-insurance-predictor:latest ${{ secrets.DOCKER_USERNAME }}/mloan-approval-predictor:latest

    # Step 9: Push Docker image to DockerHub
    - name: Push Docker image to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/loan-approval-predictor:latest